# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d75b53ddd311e2945246b65507909cca9071ebb2418e9cd5fa5f9ade310a8ed9d6da953cb75cc36b38b8b9d8cdaf58a2efa2eb0084fbc676fbbb5c848732bb43

test:
  secret_key_base: 1e46834844394f31426dcef6f66960ea4b37f8bff52e8b28c4631848f40b42f7090142a72f546787c83d34ca3443134cd709b8de5f89df751b1dc9f090da069d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
